paginate: 10
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
  
permalink: /blog/:year/:month/:day/:title/

pagination_roots: ["/blog"]

title: "A Passion Developer"
subtitle: "Senior full-stack .NET developer"

author: "Vu Hai Do"
email: "dohaivu@gmail.com"

tag_dir: "tags"
category_dir: "categories"

production_url: "dohaivu.github.io"
rss_path: "/rss.xml"

exclude: [Rakefile, Gemfile.lock, Gemfile, dohaivu.github.io.sublime-project, dohaivu.github.io.sublime-workspace]