paginate: 10
pygments: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
  
permalink: /blog/:year/:month/:day/:title/

pagination_roots: ["/blog"]

sitename: "Vu Hai Do"
subtitle: "Senior full-stack .NET developer"

author: "Vu Hai Do"
email: "dohaivu@gmail.com"

tag_dir: "blog/tag"